### ISSUE TITLE
graphql-js compatibility with versions <0.12

### ISSUE THREAD

**Issue by yoadsn** [graphql-compose/graphql-compose#111]
@nodkz I have upgraded some older project and noticed the new `graphql-compose` V3 is not compatible with graphql-js < V0.12.

The problem I stumbled upon was creating an enum value (Sort args within `graphql-compose-mongoose`).
This creation uses the new SchemaComposer method `getOrCreateETC`.
This method first creates an empty `EnumTypeComposer` (no fields) and then populates with fields. See [here](https://github.com/graphql-compose/graphql-compose/blob/06b70e2d56e7055b5a879f2d4dc286641b3f0d02/src/SchemaComposer.js#L139-L145).
When creating a named empty `EnumTypeComposer` - internally it creates an empty `GraphQLEnumType`. see [here](https://github.com/graphql-compose/graphql-compose/blob/06b70e2d56e7055b5a879f2d4dc286641b3f0d02/src/EnumTypeComposer.js#L38-L41);

Up until `graphql-js` V0.12 there was a check the makes sure field list is not empty. see [here](https://github.com/graphql/graphql-js/blob/e236ca23e26bff89de2e05cc95ba179d253662fd/src/type/definition.js#L1013-L1016);
Since V0.12 - This check was apparently removed.

See a [working](https://codesandbox.io/s/l4179o78p7) vs [failing](https://codesandbox.io/s/6xom130l3n) reproduces based on `graphql-js` version difference alone.

Should we implement a fix to support backward version? Update peer dependencies?

**Comment by nodkz** [comment]
Thanks, for detailed reporting. It was easy to fix. 😉
