### ISSUE TITLE
Relay -  RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by stoffern** [graphql-compose/graphql-compose#113]
I know this is a problem with the relay-compiler, but have you come into this problem and solved it?
@nodkz 

I will close the issue after a answer 😉

**Comment by nodkz** [comment]
I saw `RangeError: Maximum call stack size exceeded` in Relay repo, but did not meet with this problem in our app. So no advice from me. 

How I know in some cases this issue was resolved by `relay-compiler@1.5.0`.

**Comment by stoffern** [comment]
The problem is that i have example:
```js
cars{
	road{
		cars
	}
}
```
and when the compiler generates it goes into a loop when there are objects related to eachother.
Anways i will try relay-compiler@1.5.0 and see if it works

**Comment by stoffern** [comment]
I am on to something..

I have traced down the error to be related to: `filter:`
looks like it is related to .addFilterArg somehow.

here is the code:
 ```js
 {
    resolver: () => OffersTC.get('$connection')
    .addSortArg({
       name: 'POSTED',
       description: ' Sort after expiration',
       value: { postedAt: 1 },
    })
    .addFilterArg({
      name: 'expireDdate',
      type: 'String',
      description: 'Filter after date',
      query: (query, value, resolveParams) => {
      },
    })
    .wrapResolve( next => async rp => {
      rp.rawQuery = rp.rawQuery || {}
      rp.rawQuery = { 
        _id: { $in: rp.source.offerIds },
      }
      if (rp.args.filter && rp.args.filter.date)
        Object.assign(rp.rawQuery, {publishAt: { $lt: Date.parse(rp.args.filter.date) }})

      return next(rp)
    }),
    projection: { _id: 1, offerIds: 1 },
  }
```

The schema generated is correct. but When relay-compiler looks into argsInput it fails when going into a second filterArgsInput object.

Is there a way to set args outside filter to test? I think its because of the 2 layers deep Input objects in .graphql

@nodkz

**Comment by nodkz** [comment]
No matter how many layers of `wrapArgs` was used. In the built schema, it will be just regular arg map config. Suppose that you reach some crazy edge case which does not support by `relay-compiler`.

**Comment by stoffern** [comment]
@nodkz I think you misunderstood my last update. The problem is with relay-compiler, and the problem is when you use example:
shops(first: 10, filter: {name: "name"})
the relay-compiler@1.5.0 cant handle a second Input then it fails.

If you pass variable into QueryRender that has $filter: FilterFindManyShopsInput the relay-compiler will throw .exeption error 😉

**Comment by nodkz** [comment]
In our app we use variables with queries and they work like a charm without any errors: 
```js
<QueryRenderer
  environment={relayEnv}
  query={graphql`
    query ExampleQuery($first: Int!, $filter: FilterFindManyShopsInput) {
      viewer {
        shops(first: $first, filter: $filter) {
          someData
        }
      }
    }
  `}
  variables={{ first: 10, filter: {name: "name"} }}
  render={({error, props}) => {
    if (error) {
      return <View><Text>{error.message}</Text></View>;
    } else if (props) {
      return <View><Text>Render conponent with data: {JSON.stringify(props)}</Text></View>;
    }
    return <View><Text>Loading</Text></View>;
  }}
/>
```

**Comment by stoffern** [comment]
Wierd do you also pass the filter variable to subcomponents or relay containers

**Comment by nodkz** [comment]
Variables are available in relay context. So you may read them from there.

Using variables from my example above in relay-modern is proper way of writing queries. Also if you want to migrate on persistent queries in future, you will also need to declare vars on query level.

**Comment by stoffern** [comment]
hm.. cant not understand this, what am i doing wrong?

```js



UserCategories = createFragmentContainer(
  UserCategories,
  graphql`
  fragment UserCategories_query on Viewer {
    categories {
      _id
      name
    }
    users(filter: $filter){
      categoryIds
    }
  }
`
);

  return (
    <QueryRenderer
      environment={RelayEnvironment}
      query={graphql`
          query UserCategoriesQuery (
            $filter: FilterFindManyUserInput
          ) {
            viewer{
              ...UserCategories_query
            }
          }
        `}
      variables={{
        filter: { _id: _id }
      }}
      render={({ error, props }) => {
        if (error) mainProps.actions.logout();
        else if (props)
          return <UserCategories query={props.viewer} {...mainProps} />;
        else return null;
      }}
    />
  );
```

**Comment by stoffern** [comment]
Just found this https://github.com/facebook/relay/issues/2292 😞

**Comment by nodkz** [comment]
Now we are using react-relay@1.4.1 without args definitions, like your code above. And all works fine.
Just using better naming - take fragment typename and make it lowercased for property name:
```diff
- fragment UserCategories_query on Viewer {
+ fragment UserCategories_viewer on Viewer {

- ...UserCategories_query
+ ...UserCategories_viewer

- return <UserCategories query={props.viewer} {...mainProps} />;
+ return <UserCategories viewer={props.viewer} {...mainProps} />;
```
