### ISSUE TITLE
[Feature] TC.addResolvers

### ISSUE THREAD

**Issue by stoffern** [graphql-compose/graphql-compose#123]
Add possibility for adding multiple resolvers at once.

**Comment by nodkz** [comment]
It's not a problem to add such method, but I do not want blow up API to much.
Do you think that it's common task? 
Or it may be used in your plugins via one line code:
```js
myResolvers.forEach(r => tc.addResolver(r));
```

**Comment by stoffern** [comment]
What about addFields() ? 😄

**Comment by nodkz** [comment]
Yep, this is often used method in our app. Already implemented 😉
https://graphql-compose.github.io/docs/en/api-TypeComposer.html#addfields

**Comment by stoffern** [comment]
Its wierd that addFields exists and addResolvers dont 😕 hehe
I would really need addResolvers to, in example doing dynamodb resolvers 😇

**Comment by nodkz** [comment]
Heh. It's very simple. What I use more than several times in the code of our app I add as one line helper.

So I'm happy to add addResolvers if it reduce your code. Feel free to open PR and it will be merged even if i do not use your method. Just required any proper use case. Your PR and strongly feeling will be enought for such improvement.
