### ISSUE TITLE
How best to allow file uploads in GraphQL

### ISSUE THREAD

**Issue by mattslight** [graphql-compose/graphql-compose#127]
I would like to provide a file upload ability through my GraphQL server. I am looking at implementing an Apollo plugin [jaydenseric/apollo-upload-server](https://github.com/jaydenseric/apollo-upload-server)

In the docs it creates a new scalar and Upload resolver from graphql-tools:-

```javascript
import { makeExecutableSchema } from 'graphql-tools'
import { GraphQLUpload } from 'apollo-upload-server'

const schema = makeExecutableSchema({
  typeDefs: `scalar Upload`,
  resolvers: { Upload: GraphQLUpload }
})
```

How could I achieve the same through graphql-compose? (I have read through your helpful documentation but I am confusing myself). Any help most appreciated.

**Comment by mattslight** [comment]
D'oh, I missed the obvious step by step instructions here:

[graphql-compose-boilerplate-upload](https://github.com/graphql-compose/graphql-compose-boilerplate-upload)

**Comment by riggedCoinflip** [comment]
The link to https://graphql-compose.github.io/docs/en/guide-file-uploads.html is broken by now.
