### ISSUE TITLE
Grouping mutation

### ISSUE THREAD

**Issue by trungtin** [graphql-compose/graphql-compose#128]
Thank you for top notch work here.

But how do we grouping mutations? Or generally, how do we define a new grouping type?

For example, I have this:

```
const postMutations = {
  createPost: new Resolver(...),
  upvotePost: new Resolver(...)
}

// This work perfectly well
schemaComposer.rootMutation().addFields({
  ...postMutations
})
```
But based on playing around with graphql-compose type definition I thought this would work, but it doesn't
```
schemaComposer.rootMutation().addFields({
  PostMutation: {
    type: schemaComposer.TypeComposer.create({
      name: 'PostMutation',
      fields: {
        ...postMutations,
      },
    }),
    args: {
      postId: 'String!',
    },
  },
})
```

In the end, I just want to write a mutation like this
```
mutation {
  PostMutation(postId:"") {
     upvotePost {...}
  }
}
```

Best,

**Comment by stoffern** [comment]
After the GraphQL standard it is not possible to have nested mutations.
They are root only. 

https://github.com/graphql/graphql-js/issues/672

**Comment by nodkz** [comment]
@trungtin sorry for my late response.

You may use Grouping mutation with `graphql-compose` it's exactly what I do in my app, but without `args` grouping.
I'm using them in such way:
```js
schemaComposer.Mutation.addNestedFields({ . // <------------   addNestedFields automatically creates sub-types
    'admMutation.page.create': PageTC.getResolver('createOne'),
    'admMutation.page.update': PageTC.getResolver('updateById'),
    'admMutation.page.remove': PageTC.getResolver('removeById'),
})
```

In your case, you should do some tricks with `info` property in `resolve` method. Very bogus way ;)
```js
schemaComposer.Mutation.addFields({
  PostMutation: {
    type: schemaComposer.TypeComposer.create({
      name: 'PostMutation',
      fields: {
        ...postMutations,
      },
    }),
    args: {
      postId: 'String!',
    },
    resolve: (source, args, context, info) => {
       const NEW_ARG_AST = combine_data_from(args + info);
       info._FIND_PLACE_TO_MODIFY_QUERY_AST_ = NEW_ARG_AST;
       return {};
    },
    // other way less tricky, but also bogus
   resolve: (source, args, context, info) => {
       // you pass `args` as `source` for underlying resolvers
       // BUT you need cook your own resolvers in such way, that they accepts args from `source` 
       return { args };
    },
  },
})
```

**Comment by nodkz** [comment]
So I do not recommend you to do such mutations (like in your case - moving args on one level up). 
Your consumers may get problems with static analysis checks on their side (Relay, Apollo Client). It looks like you want to help, but it will not. 😈
