### ISSUE TITLE
Why do we have `projection` field on GraphqlFieldConfigExtended

### ISSUE THREAD

**Issue by mernxl** [graphql-compose/graphql-compose#129]
https://github.com/graphql-compose/graphql-compose/blob/fe60a999e5dee24ebbace7d5ed31c5934f2f8636/src/TypeComposer.js#L82

Hello, i was working with `graphql-compose-mongoose`, when i created some virtuals on `mongoose model`, i would set the required fields to generate such virtuals on the projection field of fieldsConfig e.g.

```js
InvoiceSchema.virtual('value').get(function (this: IInvoice) {
  return (this.discount) ?
    this.realValue - ((this.discount.percent * this.realValue) / 100) : this.realValue;
});

// ... other setups ... 

InvoiceTC.addFields({
    value: {
    type: GraphQLFloat,
    projection: { realValue: 1, discount: 1 },
    description: 'Payable Invoice Value, i.e. plus Discount',
  },
})
```
With the above, i expected to query and receive the right virtuals, but i keep on receiving `null`. 
So i wanted to ask, what is the use of the `projection` property on `GraphqlFieldConfigExtended`??

**Comment by nodkz** [comment]
First of all, I recommend using `loadClass` method from mongoose:
http://mongoosejs.com/docs/api.html#schema_Schema-loadClass
https://gist.github.com/nodkz/812519ca9473b28493122872ae57e9c3#file-user-js-L206
It helps to provide safer static definitions (you be able to use `InvoiceDoc` type in future definitions):
```js
class InvoiceDoc {
  get value(): number {
    return (this.discount) ?
    this.realValue - ((this.discount.percent * this.realValue) / 100) : this.realValue;
  }
}
InvoiceSchema.loadClass(InvoiceDoc);
```

--------
About `projection` property in `GraphqlFieldConfigExtended`. It does exactly what you describe.
It must populate fields for your virtual field. I suppose that you have an error in your code.

Try such code:
```diff
- InvoiceSchema.virtual('value').get(function (this: IInvoice) {
+ InvoiceSchema.virtual('value').get(function () {
  return (this.discount) ?
    this.realValue - ((this.discount.percent * this.realValue) / 100) : this.realValue;
});
```

**Comment by mernxl** [comment]
The code is ok, I am using typeScript. The `(this: IInvoice)` will be striped off at transpile. 
I will definitely use the `loadClass`, will work well with typescript.

Actually, when I log the data (source), I don't see `discount`, `realValue` fields being projected.

```js
 InvoiceSchema.virtual('value').get(function () {
  console.log(this);  +++
  return (this.discount) ?
    this.realValue - ((this.discount.percent * this.realValue) / 100) : this.realValue;
});
```

**Comment by mernxl** [comment]
Hey @nodkz, after checking up, i found out that, the `projection` issue only comes up when using `Discriminators`. The childTCs project well but the baseTC doesn't. Got a feeling issue might be because we are using `InterfaceType` as Output types for baseTC.
