### ISSUE TITLE
[help] Filter arg only matching first object in array with compose-mongoose

### ISSUE THREAD

**Issue by mattslight** [graphql-compose/graphql-compose#132]
Hi @nodkz I am using filter arg across an array composed by mongoose schema and I only seem to be able to match the first object in the array. Is this a limitation of the filter arg or am I doing something wrong?

Thanks in advance.

Full schema, queries and output below...

I am using graphql-compose-mongoose with following schema:-

```javascript
const MessageSchema = mongoose
	.Schema({
		recipients: [
			{
				kind: { type: String, enum: ['User', 'Class'], required: [true, 'required'] },
				id: {
					type: mongoose.Schema.Types.ObjectId,
					refPath: 'recipients.kind'
				}
			}
		]
	})

const Message = mongoose.model('Message', MessageSchema)
const MessageTC = composeWithMongoose(Message)

schemaComposer.rootQuery().addFields({
	messageById: MessageTC.getResolver('findById'),
	messageByIds: MessageTC.getResolver('findByIds'),
	messageMany: MessageTC.getResolver('findMany'),
	messageCount: MessageTC.getResolver('count')
})
```

and I have the following MongoDB document:-

```javascript
{ 
    "_id" : ObjectId("5b70712b844c9abcd65b20aa"), 
    "recipients" : [
        {
            "kind" : "Class", 
            "id" : ObjectId("5b4708b9c513d3709ff44d98")
        }, 
        {
            "kind" : "User", 
            "id" : ObjectId("5b4707f8c513d3709ff44d96")
        }
    ]
}
```

When I use filter arg to findMany messages by recipients.id the first object is found:-

```javascript
query messagesByUserId {
  messageMany(filter: {recipients: {id: "5b4708b9c513d3709ff44d98"}}) {
    _id
  }
}

--- graphiql output ---
{
  "data": {
    "messageMany": [
      {
        "_id": "5b70712b844c9abcd65b20aa"
      }
    ]
  }
}
```

but not the second:-
```javascript
query messagesByUserId {
  messageMany(filter: {recipients: {id: "5b4707f8c513d3709ff44d96"}}) {
    _id
  }
}

--- graphiql output ---
{
  "data": {
    "messageMany": []
  }
}
```

If I reverse the order of the recipients array then it finds the object ending `4d96` but not the second. So it seems that the filter arg is only matching against the first object in the array. Am I doing something wrong? TIA

**Comment by nodkz** [comment]
It's default behavior of MongoDB to search in the first object in the array field.

For your case, you need to use [$elemMatch](https://docs.mongodb.com/manual/reference/operator/query/elemMatch/)

And of course, write a custom filtering argument:
```js
	MessageTC.getResolver('findMany').addFilterArg({
		name: 'recipientIds',
		type: 'MongoID',
		description: 'Search by recipients',
		query: (rawQuery, value) => {
			rawQuery.recipients = { $elemMatch: { id: value } }
		}
	})
```

Ping me if it helps.

**Comment by mattslight** [comment]
works like a charm - thank you

**Comment by gvbkr** [comment]
@mattslight  @nodkz I am running into the same problem. When I follow the addFilterArg method, I observe that the filter is being added instead of being overwritten. So in effect it executes a query with with both individual elements AND also with the new custom filter. 

Is there anyway to just overwrite that instead of adding the filter?
```
MessagePagination: MessageTC.getResolver('pagination').addFilterArg({
    name: 'dtags',
    type: '[String]',
    description: 'Search by dtags array',
    query: (rawQuery, value) => {
      rawQuery.dtags = { $elemMatch: { $in: value } };
    },
  }),

# This is the log from mongoose in debug mode. 
Mongoose: messages.find({ 'dtags.0': 'ba-fav', 'dtags.1': 'BaseTestSet50', dtags: { '$elemMatch': { '$in': [ 'ba-fav', 'BaseTestSet50' ] } } },


# If I remove the custom addFilterArg, I see the following in Mongo
Mongoose: nerresults.find({ 'dtags.0': 'ba-fav', 'dtags.1': 'vg-fav' }
```

Any help is greatly appreciated, currently I am blocked. The use case is searching objects by any of a list of tags associated with that object.

**Comment by nodkz** [comment]
@gvbkr as fast solution just rename your argument:
```diff
MessagePagination: MessageTC.getResolver('pagination').addFilterArg({
-    name: 'dtags',
+    name: 'dtagsIn',
    type: '[String]',
    description: 'Search by dtags array',
    query: (rawQuery, value) => {
      rawQuery.dtags = { $elemMatch: { $in: value } };
    },
  }),
```

**Comment by nodkz** [comment]
Also you may remove `filter.dtags` value after providing it to `rawQuery`:

```js
MessagePagination: MessageTC.getResolver('pagination').addFilterArg({
    name: 'dtags',
    type: '[String]',
    description: 'Search by dtags array',
    query: (rawQuery, value, resolveParams) => {
      rawQuery.dtags = { $elemMatch: { $in: value } };
      delete resolveParams.args.dtags;
    },
  }),
```

**Comment by gvbkr** [comment]
The first solution did the trick!! I will try the second one that looks more cleaner.

**Comment by mattslight** [comment]
Out of interest @nodkz is there a setFilterArg? I'm AFK to check the docs.

M

**Comment by nodkz** [comment]
@mattslight nope, no `setFilterArg` nor `removeFilterArg`. Only `addFilterArg()`. 

It was added as an experimental feature a couple years ago. I'm widely using this method in my apps.
But I still did not gather best practices for this part. I have strong filling that it should be solved somehow differently, but still don't know how. I'm open to your ideas and suggestions.
