### ISSUE TITLE
circular data structure not supported with graphql-compose-dataloader

### ISSUE THREAD

**Issue by tanekim77** [graphql-compose/graphql-compose#136]
Suppose
Teacher mongoose model has students list,
but each student can be teacher of anyone, including the current teacher.
```
const TeacherSchema= new Schema(
  {

    students: [{
      type:Schema.Types.ObjectId,
      ref:'Student',
    }],
  }
);

const StudentSchema= new Schema(
  {

    teacher: {
      type:Schema.Types.ObjectId,
      ref:'Teacher',
    },
  }
);


```
If I use composeWithMongoose and composeWithDataLoader, and create one teacher and search for one teacher using getResolver("findOne"),
it is throwing error, citing JSON.stringify does not support circular structure. If I do not use composeWithDataLoader, circular structure is working and is supported.

**Comment by nodkz** [comment]
There is no problem with `graphql-compose`.

This issue should be addressed to graphql-compose-dataloader repo: 
https://github.com/graphql-compose/graphql-compose-dataloader/issues/4

Thanks.
