### ISSUE TITLE
Interface document?

### ISSUE THREAD

**Issue by tanekim77** [graphql-compose/graphql-compose#137]
According to Basics=>"Type creation" 's bottom section, it says, "Interfaces
Graphql-compose does not provide any helper for Interfaces. You should use standard GraphQLInterfaceType."
But in the API Reference section, I see InterfaceTypeComposer Section, which seems to be helper for Interface. Which part of the document should I rely on?

**Comment by mernxl** [comment]
Hey @tanekim77, InterfaceTypeComposer was recently added, we just need to update the docs. You can use the InterfaceTypeComposer, it's stable already. It's actually being used by `DiscriminatorTypeComposer` on graphql-compose-mongoose to deal with collection level Discriminators.

**Comment by nodkz** [comment]
Thanks for pointing on this stale information. 
Fixed.
