### ISSUE TITLE
Is there a way to avoid N+1 queries

### ISSUE THREAD

**Issue by akaNightmare** [graphql-compose/graphql-compose#140]
Hello,

I have a simple query with _1:N_ relation between User (1) : Store(N) models and see that there a lot of queries:
![image](https://user-images.githubusercontent.com/4151616/47252979-ceb3d200-d455-11e8-9e5f-62c7f07e2de0.png)
I am wondering if there any way to avoid this (like graphql-sequelize do https://github.com/mickhansen/dataloader-sequelize), current _graphql-compose-dataloader_ cannot do that?

Thanks,

**Comment by nodkz** [comment]
[graphql-compose-dataloader](https://github.com/graphql-compose/graphql-compose-dataloader) was written by @stoffern and should work as it described in its readme.md. 

Also if you don't like its behavior you may write your solution, it will not take too much time:
https://github.com/graphql-compose/graphql-compose-dataloader/blob/master/src/composeWithDataLoader.js

PS. I just write an article in Russian about the proper way of using DataLoader: https://github.com/nodkz/conf-talks/tree/master/particles/graphql/dataloader 

Hope that provided information helps. Sorry for the late response, too busy at the end of the year.

**Comment by akaNightmare** [comment]
@nodkz Thanks a lot.
