### ISSUE TITLE
toInputObjectType should check for list of abstract types

### ISSUE THREAD

**Issue by stefanprobst** [graphql-compose/graphql-compose#141]
When trying to convert to InputObjectType, `toInputObjectType` [checks `isAbstractType`](https://github.com/graphql-compose/graphql-compose/blob/ed8b185ee8468f3ef4641854802537fb8ed40c2f/src/utils/toInputObjectType.js#L62) before calling `convertInputObjectField`.

This prevents Interface types to be converted, but *does* try to convert *lists* of abstract types, [which then fails](https://github.com/graphql-compose/graphql-compose/blob/ed8b185ee8468f3ef4641854802537fb8ed40c2f/src/utils/toInputObjectType.js#L106). The same is true for non-nullable abstract types.

**Comment by stefanprobst** [comment]
Sounds good to me!

**Comment by nodkz** [comment]
Will land in v5.3.2

**Comment by stefanprobst** [comment]
Thanks!

**Comment by stefanprobst** [comment]
Should nested interface fields also be supported in `toInputObjectType`? Currently [`convertInputObjectField` checks for `GraphQLObjectType`](https://github.com/graphql-compose/graphql-compose/blob/16beaea166e920b8f88b4d51d9484e96b4321219/src/utils/toInputObjectType.js#L102) -- maybe it should just check for `isOutputType`?

I am thinking of type defs like this:
```graphql
interface Node {
  parent: Node
  children: [Node]
}
type Thing implements Node {
  parent: Node
  children: [Node]
  something: String
}
```

**Comment by nodkz** [comment]
Should!

Can you make PR?

**Comment by stefanprobst** [comment]
Sure!
