### ISSUE TITLE
SchemaComposer.removeEmptyTypes should handle interface types

### ISSUE THREAD

**Issue by stefanprobst** [graphql-compose/graphql-compose#144]
It seems that currently, `schemaComposer.buildSchema()` will not include all types implementing an interface, e.g.
```graphql
type Foo implements IFace {...}
type Bar implements IFace {...}
type Example {
  foo: IFace
}
```
should include both Foo and Bar.

I think the issue is in [`SchemaComposer.removeEmptyTypes`](https://github.com/graphql-compose/graphql-compose/blob/16beaea166e920b8f88b4d51d9484e96b4321219/src/SchemaComposer.js#L167).

**Comment by nodkz** [comment]
Currently we cannot automatically provide object types from interfaces to the schema.

You should include `Foo` and `Bar` types explicitly to the schema:
```js
sc.addSchemaMustHaveType(Foo);
sc.addSchemaMustHaveType(Bar);
```
https://graphql-compose.github.io/docs/en/api-SchemaComposer.html#addschemamusthavetype

--------
If you define Foo and Bar via SDL, then you

**Comment by stefanprobst** [comment]
Ah, should have read more carefully. Thanks!
