### ISSUE TITLE
Set Resolver Output to required

### ISSUE THREAD

**Issue by rockus123** [graphql-compose/graphql-compose#155]

**Comment by rockus123** [comment]
Hi,

It seems there's no api to change the output of say findMany, findOne to required.

**Comment by nodkz** [comment]
Please take a look on this issue https://github.com/graphql-compose/graphql-compose-mongoose/issues/144#issuecomment-446281355

**Comment by nodkz** [comment]
It makes agrs required, but the same methods work for getTC method in Resolver

**Comment by rockus123** [comment]
Thanks nodkz.
