### ISSUE TITLE
Is there a way to add two or more filters to input?

### ISSUE THREAD

**Issue by rockus123** [graphql-compose/graphql-compose#156]
Hi,

I wonder if there's a way to add 2 or more filter to input.  For example,

```
query Parent(filter, sort, skip,  sort, limit, filterChild) {
   parentField1
   Child {
      childField1
  }
}
```

I would like to request and on the server side query for the child with a certain filterChild (formed from FilterFindMany filter) and then use the list of child to get the parent $in clause to get the list of parent and using the parent filter. 

 In effect, what I wanted is to retrieve the list of parents based on the parent filter that has these child(ren) base on filterChild.  If the child doesn't match the filterChild criteria, the parent should be in the final returned parent list.  And reuse the richness of both existing filters of the FilterFindMany models and their extensions.

I cannot do this because it will return Parent with Child matching filterChild but also Child with null (not matching filterChild) too.

```
query Parent(filter, sort, skip,  sort, limit) {
   parentField1
   Child(filterChild) {
      childField1
  }
}
```

I try using addArgs({"filterChild": "FilterFindManyChild"}) but was unsuccessful: 

```
schemaComposer.Query.addFields({
   parentManyWithFilterChild:  ParentTC.getResolver('findMany').wrapCloneArg('filter', 'FilterFindManyParent').addArgs({"filterChild": "FilterFindManyChild"}).wrapResolve(next=>async (rp) => {
  // childList = ChildTC.findMany(filterChild)
  // parentList = ParentTC.findMany(filter against childList (with $in clause) and also against parentField1)
  // return parentList
})
```
Thanks.

**Comment by nodkz** [comment]
Clients should write queries correctly. Do not rename `filter` to `childFilter`!

```graphql
query MyComplexQueryWithVariables($ParentFilter: FilterFindManyParent!, $ChildFilter: FilterFindManyChild!) {
   parent(filter: $ParentFilter) {
     parentField1
     child(filter: $ChildFilter) {
        childField1
     }
   }
}
```

**Comment by nodkz** [comment]
If you need some complex cases, then better to write a new custom resolver with custom filtering from scratch. In most cases it more comfortable to understand what happens, rather than wrapping.

**Comment by rockus123** [comment]
Thanks nodkz.  There are so many names, so many structures.  It takes some trial and error but now I am able to resolve the issue by using:

`childResolver.addArgs({"childFilterInParentArg": childTypeComposer.getResolver('findMany').getArg("filter").`
