### ISSUE TITLE
[Feature] Knex adapter

### ISSUE THREAD

**Issue by stoffern** [graphql-compose/graphql-compose#16]
Create `graphql-compose-caminte`
https://github.com/biggora/caminte

**Comment by nodkz** [comment]
I do not believe in silver bullet, that supports sql and nosql DBs. I think that `caminte` provide only basic operations and can bring problems for developers in future, when they needed some specific behavior. I will not use it in my app, and can not provide good support for `caminte`.

But I will be very happy if somebody create such adapter, who use it in their app.

**Comment by cellis** [comment]
@nodkz I would like to write a graphql plugin like this, but on top of knex instead of an orm. Reason: I like what you're doing with graphql-compose and would rather piggyback on what you've got going than rewrite my own "type composer", but I want to also do things like postgraphql's ACL/ authorization

**Comment by nodkz** [comment]
Wow. Will be cool!
First time see knex and say that I'd like it.
Feel free to create your own plugin. I will help you with reviews and suggestions, and will try to answer your questions as fast as possible due my current load.

Try to build it on top of `graphql-compose` in future it allows to combine different dbs in one schema. Right now api of graphql-compose is stable. And it allows to create schemas with any type of db, rest services. Graphql-compose just bunch of useful methods that allows to create/edit graphql types and relate them. You may offer any additional useful methods (but try to keep them agnostic to db/data-sources). 

All specific logic according to db/data source should be placed in separate plugin. Like `graphql-compose-mongoose` plugin, which is build on top of `graphql-compose` and do all mongoose tricks in it.

ACL may be also be provided as separate plugin, like `graphql-compose-relay`, which takes TypeComposer and tune/extend it with Relay specific things.

PS. Will be cool if you share your "type composer" for me. I think, that I can find new fresh ideas for future improvements.

**Comment by cellis** [comment]
@nodkz will do. Btw, what tool do you use to give things in commits like (feat), chore(build): docs(Changelog).

**Comment by nodkz** [comment]
@cellis i'm using commitizen and semantic release for automatic versioning and NPM releasing.
Recommend to see Kent Dodds' awesome tutorials: https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-writing-conventional-commits-with-commitizen

**Comment by stoffern** [comment]
@cellis Great!

I think that a plugin based on Knex would be way better then on Caminte 👍
Will let this issue be open until the adapter is in place 😉

**Comment by nodkz** [comment]
Knex does not have models. Close this issue.

New conversation with sequalize: https://github.com/graphql-compose/graphql-compose/issues/148
