### ISSUE TITLE
UnionTypeComposer.getType().getTypes() not working

### ISSUE THREAD

**Issue by stefanprobst** [graphql-compose/graphql-compose#167]
Calling `SomeUTC.getTypes()` works as expected, but `SomeUTC.getType().getTypes()` does not, seems necessary to call `SomeUTC.getType().getTypes()()`. Haven't quite figured out yet where this is happening.

**Comment by nodkz** [comment]
Very strange, needs code demo or test case

**Comment by stefanprobst** [comment]
Ok, this seems to only happen with graphql@0.13, something changed concerning `gqType._types`, will investigate. You can check with:
```js
const { TypeComposer, UnionTypeComposer } = require('graphql-compose')
const Foo = TypeComposer.create('type Foo { foo: String }')
const Bar = TypeComposer.create('type Bar { bar: String }')
const Union = UnionTypeComposer.create('Union')
Union.setTypes([Foo, Bar])

// graphql@14
console.log(Union.getType().getTypes())

// graphql@0.13
// console.log(Union.getType().getTypes()())

```

**Comment by stefanprobst** [comment]
0.13.2
`_types: Array<GraphQLObjectType>;`
https://github.com/graphql/graphql-js/blob/f995c1f92e94d9c451104b6a0db8034165ef8640/src/type/definition.js#L987

14.1
`_types: Thunk<Array<GraphQLObjectType>>;`
https://github.com/graphql/graphql-js/blob/d55f6d364ada22c122c718ddf74951b20ef0b17b/src/type/definition.js#L1049

**Comment by nodkz** [comment]
Thanks for the investigation. I'll try to fix this today at evening.
