### ISSUE TITLE
extendField should extend field extensions

### ISSUE THREAD

**Issue by stefanprobst** [graphql-compose/graphql-compose#177]
Currently, `extendField` overwrites an existing `extensions` field property. I think it would be better if both extensions are merged?

```js
const { ObjectTypeComposer, SchemaComposer } = require('graphql-compose');

const sc = new SchemaComposer();

const tc = ObjectTypeComposer.create(
  {
    name: 'Test',
    fields: {
      test: {
        type: 'String',
        extensions: { test: true },
      },
    },
  },
  sc
);

tc.extendField('test', {
  resolve: source => source.test,
  extensions: { added: true },
});

console.log(tc.getFieldExtensions('test'));
// { added: true }
// Should be { test: true, added: true }
```

**Comment by nodkz** [comment]
Agreed with you. 👍
Can you sync with @freiksenet with this change?

And he also agreed can you make Pull Request?

**Comment by nodkz** [comment]
I think that he is sleeping right now. So you may make Pull Request and we await his approving.

**Comment by freiksenet** [comment]
Yeah, I agree this is a better behavior. This is just an oversight on my part.
