### ISSUE TITLE
Error when merging existing schema

### ISSUE THREAD

**Issue by major-mann** [graphql-compose/graphql-compose#186]
When attempting to merge an existing schema using the `merge` function on `SchemaComposer`, an error occurs when calling buildSchema

    const composer = new SchemaComposer();
    composer.Query.addFields({
        test: {
            type: 'String!',
            resolve: () => 'test field value!'
        }
    });

    // Have attempted passing in the constructor here and calling composer2.merge
    const composer2 = new SchemaComposer(composer.buildSchema());
    // composer2.merge(composer.buildSchema());
    composer2.Query.addFields({
        test2: {
            type: 'String!',
            resolve: () => 'test2 field value!'
        }
    });
    
    // Causes: Error: Query.test should provide "deprecationReason" instead of "isDeprecated"
    composer2.buildSchema();

This error seems to also happen for schemas which were not created using the composer

**Comment by nodkz** [comment]
Fixed in 6.3.1
Thanks!

**Comment by major-mann** [comment]
> Fixed in 6.3.1

Any ETA for that on NPM?

**Comment by nodkz** [comment]
In 1 minute

**Comment by major-mann** [comment]
Can confirm a working field test! Ty!
