### ISSUE TITLE
How to tell graphql to ignore fields that not exist in the schema?

### ISSUE THREAD

**Issue by wizardnet972** [graphql-compose/graphql-compose#192]
How can `graphql` ignore fields that not in the schema?

For example, when I send the mutation request with a field that not exist (`bla: true`) on the schema I got the following error: 

```
    {"errors":[{"message":"Variable \"$collections\" got invalid value [{ name: \"ss\", bla: true }, { name: \"aaa\" }]; Field \"bla\" is not defined by type MyInput at value[0].","locations":[{"line":1,"column":25}]}]}
```

**Comment by nodkz** [comment]
It's not impossible by [graphql-spec](https://github.com/graphql/graphql-spec). 
You MUST provide only allowed fields by the schema.

(The problem is not in this package).

**Comment by nodkz** [comment]
Under the hood `graphql-compose` uses [graphql-js](https://github.com/graphql/graphql-js) package for runtime. So if graphql-js will support it then graphql-compose will automatically provide such ability.

But as I said for not it's impossible and not supported in graphql-js.

**Comment by wizardnet972** [comment]
Okay.

The motivation behind that is to add some field on the collection object (that for internal use) and then send this object back to the graphql for update the collection.

The mongoose is ignored any field that not on the schema, and that makes it more comfortable.

Hope graphql will implement this one day :)
