### ISSUE TITLE
Adding new Scalar Types

### ISSUE THREAD

**Issue by MDrooker** [graphql-compose/graphql-compose#194]
What would the best/proper way to add new scalar types from other modules?
I am trying to use a few from [https://github.com/okgrow/graphql-scalars](url).
I am using the syntax of -
```
const OKGGraphQLScalars = require('@okgrow/graphql-scalars')
const OKGScalarDefinitions = require('@okgrow/graphql-scalars').OKGScalarDefinitions
SchemaComposer.addResolveMethods(OKGGraphQLScalars);
SchemaComposer.addTypeDefs(OKGScalarDefinitions);
{ few more SchemaComposer.createObjectTC & SchemaComposer.Query.addFields }

then
const graphqlSchema = SchemaComposer.buildSchema();
```
But its getting the error-

**Must provide Source. Received: ["scalar DateTime", "scalar EmailAddress", "scalar NegativeFloat", "scalar NegativeInt", "scalar NonNegativeFloat", "scalar NonNegativeInt", "scalar NonPositiveFloat", "scalar NonPositiveInt", "scalar PhoneNumber", "scalar PositiveFloat"]**

What am I missing....seems like this should work.

**Comment by nodkz** [comment]
Try to use regular `add` method `schemaComposer.add(Scalar1); schemaComposer.add(Scalar2); ...`.

Then this types will be avaliable by string name for definition in other ObjectTypes.

**Comment by MDrooker** [comment]
Worked as described
