### ISSUE TITLE
Is it possible to use recursive type declaration?

### ISSUE THREAD

**Issue by malihs** [graphql-compose/graphql-compose#197]
I can't figure out how one could use recursive type declaration with graphql-compose. From this https://github.com/graphql/graphql-spec/issues/91 , it sounds likes it's not natively supported for security reasons. Does graphql-compose work around this issue? 
Thank you!

**Comment by nodkz** [comment]
`Recursive type declaration` at schema definition supported in GraphQL-spec (many examples across the internet about a user-friends relationship). In other words - backend developers can define fields with "recursive" types. It supported by graphql-compose.
See example `3.1 Self referenced Employee Type` at https://graphql-compose.herokuapp.com/ :

```graphql
{
  viewer {
    employeeList { # [Employee] type
      firstName
      subordinates { # self-referenced [Employee] type
        firstName
      }
      chief { # self-referenced Employee type
        firstName
      }
    }
  }
}
```

`Recursive fields in queries via fragments` in runtime does not support by security reasons by SPEC. In other words - the clients cannot make a recursive query.

**Comment by malihs** [comment]
Sorry for not replying sooner and thanks for your reply. It does make sens. What I was struggling with is how to do it with TypeComposer. It happens that I'm loading data for a Sider menu (d like the menus we see in documentations), where pages have child pages and so forth so on. I managed to get it working but il looks clunky:

```javascript
export const ThirdLevelPage = TypeComposer.create({
  name: "ThirdLevelPage",
  fields: {
    pageid: "String!",
    title: "String",
    url: "String",
    position: "String",
  }
});


export const SecondLevelPage = TypeComposer.create({
  name: "SecondLevelPage",
  fields: {
    pageid: "String!",
    title: "String",
    url: "String",
    position: "String",
    children: [ThirdLevelPage]
  }
});

export const FirstLevelPage = TypeComposer.create({
  name: "FirstLevelPage",
  fields: {
    pageid: "String!",
    title: "String",
    url: "String",
    position: "String",
    children: [SecondLevelPage]
  }
});

export const PageMany = TypeComposer.create({
  name: "PageMany",
  fields: {
    pages: [FirstLevelPage],
  }
});
``` 

Is there a cleaner/ systematic way to do this? 
Thank you very much

**Comment by nodkz** [comment]
It may be solved in such way via thunk with self-referencing:

```js
export const PageLevel = TypeComposer.create({
  name: "PageLevel",
  fields: {
    pageid: "String!",
    title: "String",
    url: "String",
    position: "String",
    children: {
       type: () => [PageLevel],
       resolve: (source, args) => { .....somehow.find.where(parentId = source.pageId)..... }
    }
  }
});

export const PageMany = schemaComposer.Query.addFields({
   pages: {
      type: [PageLevel],
      resolve: () => { ....somehow.find.where(parentId = null)..... }
   }
});
```

In such case may be any deep of menu. Your client decide how many level request via its query eg:
```graphql
{
  pages {
    title
    children {
       title
       children {
         title
         children {
           title
         }
       }
    }
  }
}
```

But be careful with N+1 Problem. You will need to use [DataLoader](https://github.com/graphql/dataloader) for your resolve method for reducing number of queries to your database.

**Comment by malihs** [comment]
Oh I see, It does make total sense, thunk will do. Thank you so much!
