### ISSUE TITLE
Type kind "ObjectTypeExtension" not supported

### ISSUE THREAD

**Issue by djflex68** [graphql-compose/graphql-compose#201]
If SDL imported by `schemaComposer.addTypeDefs(..)` contains an extended type like 
```
extend type Query {
    author(id: Int!): Author
} 
```
we get "Error: Type kind "ObjectTypeExtension" not supported. "
Any workaround for this ?

**Comment by nodkz** [comment]
`extend` operator was added in 7.4.0 somewhere a month ago
https://github.com/graphql-compose/graphql-compose/issues/142

If errors stay, please reopen the issue. Thanks.
