### ISSUE TITLE
How does UpdateById work?

### ISSUE THREAD

**Issue by smooJitter** [graphql-compose/graphql-compose#224]
How does the client side request to update a record by id works?   The input for update by id is simply $record.   How do I specify the id of the record to update?   It would seem the input for updateById would be $id and $record.

**Comment by nodkz** [comment]
Yep, for now, id and record data are mixed in one input param. It's lack in schema design. In a future major version should be splitted into two different args.

**Comment by smooJitter** [comment]
So $record argument must include a _id attribute?  Or should I specify the id through the filter arg.   Note the byId update does not have a filter argument.  It would be nice to see a full stack example that features the auto generated resolvers.  I’m looking for examples how to specify queries and mutations that are compatible with graphql-compose input types.  The example site is sufficient but it does not include an example “update query”

**Comment by nodkz** [comment]
Ouch. This is graphql-compose repo. And nothing to discuss about UpdateById here.

It should be graphql-compose-mongoose repo or you may join to another repo with schema design patterns https://github.com/graphql-rules/graphql-rules/issues/23

**Comment by nodkz** [comment]
With graphql-compose compatible any pattern of input args.

Currently some patterns exists in graphql-compose-mongoose resolvers, but as i wrote above, there are some problems with update mutation.
