### ISSUE TITLE
Strange resolvers behavior

### ISSUE THREAD

**Issue by GimignanoF** [graphql-compose/graphql-compose#226]
I have two resolvers that mostly do the same thing but on different models. Something like this

```
const resolverA = schemaComposer.createResolver({
  name: "resolverA",
  type: ImageSchema,
  args: {
    _ids: "[ID!]"
  },
  resolve: async ({ source, args, context, info }) => {
    let images;
    let id = mongoose.Types.ObjectId(args._id);
    await DocumentAModel.findOne(
      { "images._id": { $in: id } },
      { images: true, _id: false }
    )
      .lean()
      .exec()
      .then(res => {
        images = res.images;
      });
    return images.find(image => image._id.equals(args._id));
  }
});

const resolverB = schemaComposer.createResolver({
  name: "resolverB",
  type: ImageSchema,
  args: {
    _ids: "[ID!]"
  },
  resolve: async ({ source, args, context, info }) => {
    let images;
    let id = mongoose.Types.ObjectId(args._id);
    await DocumentBModel.findOne(
      { "images._id": { $in: id } },
      { images: true, _id: false }
    )
      .lean()
      .exec()
      .then(res => {
        images = res.images;
      });
    return images.find(image => image._id.equals(args._id));
  }
});

module.exports = { resolverA , resolverB };
```
Than in the schema definition I do this
```
SchemaA.getFieldOTC("metadata")
  .addRelation("image", {
    resolver: resolverA ,
    prepareArgs: {
      _id: source => source.image
    },
    projection: { image: 1 }
  });

SchemaB.getFieldOTC("metadata")
  .addRelation("image", {
    resolver: resolverB ,
    prepareArgs: {
      _id: source => source.image
    },
    projection: { image: 1 }
  });
```

The two relations are added in separate files, where I import the appropriate resolver from the resolver file.
Finally, where I build the schema I call those two files to add relations after all the schema and models has been created. What I noticed is that only the last import will work. So, I import first the relations for SchemaA and then the relations for SchemaB. If I want to get images from SchemaA then the resolverB is called, which is really strange since I specifically import resolverA where the SchemaA is defined. The same thing applies if I switch the import statements. If i split the two resolvers into two separate files everything works. So what could be the cause of this strange behaviour?

**Comment by nodkz** [comment]
Maybe some type mixing between to schemas.

```
import { SchemaComposer, schemaComposer } from 'graphql-compose';

schemaComposer // is global Instance of SchemaComposer avaliable acros all application

const schemaComposer1 = new SchemaComposer(); // your local instance of type registry/ schema
const schemaComposer2 = new SchemaComposer(); // another schema
```

So if you use `graphql-compose-mongoose` and want to generate different types for different schemas. you need to provide your schemaComposer:

```
const UserTCSchema1 = composeWithMongoose(UserModel, { schemaComposer:  schemaComposer1 });
const UserTCSchema2 = composeWithMongoose(UserModel, { schemaComposer:  schemaComposer2 });
```

**Comment by GimignanoF** [comment]
It could be type mixing since the relation will return the same type for both resolvers. Anyway I think I'll stick to separate files since is more clear "who-do-what" :)
