### ISSUE TITLE
addTypeDefs crashes with argument having default enum value [REPLAY]

### ISSUE THREAD

**Issue by V1os** [graphql-compose/graphql-compose#233]
the same error
`Error: Type with name "**" does not exist`
with use `addTypeDefs` enum

v.7.10.1

**Comment by nodkz** [comment]
Can you provide small demo of broken schema?
Tnx.

**Comment by V1os** [comment]
Ohh, it's not so easy. Have a big infrastructure. I try

```
const customTypes = \'
    enum SiteLanguage {
        en
        ru
        ua
    }
\'
```
`schemaComposer.addTypeDefs(customTypes);
schemaComposer.addResolveMethods(resolvers); // use in resolver this enum 
const schema = schemaComposer.buildSchema();
`

```
const apolloConfig = {
        schema,
       ...
    };

new ApolloServer(apolloConfig);
```

> version less than 7.10 work fine.

**Comment by nodkz** [comment]
I've just created a test case branch `233-issue` and related Pull Request  https://github.com/graphql-compose/graphql-compose/pull/234

And all is work fine according to your provided example.

It can be run via the following command:
```bash
yarn jest --runTestsByPath src/**/233-test.js
```

Can you provide additional information? Or even better modify this test with reproducing your error and open a new PR with a broken test.

Tnx.

**Comment by V1os** [comment]
@nodkz all OK. My mistake. I'm sorry
