### ISSUE TITLE
Descriptions from schema missing

### ISSUE THREAD

**Issue by cecobask** [graphql-compose/graphql-compose#239]
Hi,

I'm using compose to edit my schema 
""" Test "" 
type Note {
id: ID!
title: String!
description: String!
}

Once this schema is built using schemaComposer.buildSchema() and then 
passed to graphql-js printSchema I noticed some invalid behavior:

- Comments are missing
- Nulls are added to the fields

input Task {
  id: ID = null
  title: String = null
  description: String = null
  status: TaskStatus = null
}

**Comment by nodkz** [comment]
@cecobask the problem somewhere in your code

According to the following test case all works correctly:
https://github.com/graphql-compose/graphql-compose/blob/cc63a4c6fe67de9093bb08b53953fe56e7001204/src/__tests__/github_issues/239-test.js#L23-L27

Feel free to modify this test case to show your problem.

**Comment by wtrocki** [comment]
Thank you for blazing-fast response.
I have seen that as well and will investigate it closely
I think this could be a problem not with graphql-compose but with the `printSchema` from graphql-js. Print schema bases on the ast nodes etc. and it can print some extra stuff from AST or skip elements like comments. 

We will investigate that closer.

**Comment by nodkz** [comment]
Use built-in `schemaComposer.toSDL()` method - it more powerful that printSchema():
https://github.com/graphql-compose/graphql-compose/releases/tag/v7.11.0

**Comment by wtrocki** [comment]
This, in fact, resolves all the issues we were facing. 
Thank you so much @nodkz

**Comment by wtrocki** [comment]
Actually there is another side effects of that. 
Now all defaults scalars are printed out

```
"""
The `ID` scalar type represents a unique identifier, often used to prefetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""
scalar ID
``` 

Is that expected behavior?

**Comment by wtrocki** [comment]
Ok.. So the general update is that doing `printSchema(buildSchema(schemaComposer.toSDL()))` produces expected results without any additional changes. This way it is possible to produce schema that looks exactly like sdl schema sent to input with small alterations made directly by compose. I think this can be closed now

**Comment by nodkz** [comment]
You may use `schemaComposer.toSDL({ exclude: ['String', 'ID'] })`.

Tomorrow I'll add a new `omitScalars` option.

**Comment by nodkz** [comment]
Now you may use `schemaComposer.toSDL({ omitScalars: true })`
