### ISSUE TITLE
Directives are removed from schema in SchemaComposer

### ISSUE THREAD

**Issue by craicoverflow** [graphql-compose/graphql-compose#246]
I have a scenario where I am modifying my schema which contains a custom field directive. This directive will be lost from the schema when using SchemaComposer to modify other elements in the schema.

```ts
const schema = buildSchema(
`directive @test(
  reason: String = "No longer supported"
) on FIELD_DEFINITION | ENUM_VALUE

type ModifyMe {
  id: ID! @test(reason: "asjdk")
}

type Query {
  hello: ModifyMe
}`, { loaders: [] })

const schemaComposer = new SchemaComposer(schema);

const schemaStr = schemaComposer.toSDL({ exclude: ['ID', 'String', 'Int', 'Boolean', 'Float'] })

console.log(schemaStr)
```

The result of this will keep the directive definition, but `ModifyMe.id` will have no directive.

This does not happen when adding type definitions after constructing SchemaComposer:

```ts
const schemaString = `directive @test(
  reason: String = "No longer supported"
) on FIELD_DEFINITION | ENUM_VALUE

type ModifyMe {
  id: ID! @test(reason: "asjdk")
}

type Query {
  hello: ModifyMe
}`;

const schemaComposer = new SchemaComposer();

schemaComposer.addTypeDefs(schemaString)
```

However this is not suitable for our use case as we are operating on a GraphQLSchema object.

**Comment by nodkz** [comment]
Thanks for reporting! Will be fixed in new version.
