### ISSUE TITLE
Support for adding interfaces to other interfaces

### ISSUE THREAD

**Issue by loicmarie** [graphql-compose/graphql-compose#251]
In the latest GraphQL spec release, **interfaces can now implement other interfaces**.
It has been shipped in GraphQL JS 15.0.0 so it should already be available in this repo.

This is a very useful feature when dealing with many deeply nested subsumption relations :+1: 

Would it be possible to add `ObjectTypeComposer` interface methods to `InterfaceTypeComposer` ? 
Such as:
- `getInterfaces()`
- `getInterfacesTypes()`
- `setInterfaces()`
- `hasInterface()`
- `addInterface()`
- `addInterfaces()`
- `removeInterface()`

**Comment by nodkz** [comment]
Try to add these methods in this month.
Or you may add them yourself via Pull Request 😉

**Comment by loicmarie** [comment]
That was fast ! Thanks !
