### ISSUE TITLE
Contribution difficulties

### ISSUE THREAD

**Issue by bkoltai** [graphql-compose/graphql-compose#253]
Hi, thanks for the awesome project! I'm trying to reproduce an issue I'm seeing and wanted to pull down the repo and write a test to reproduce my issue. After cloning the repo and running `npm install`, I then try to run `npm run wtach` to get the tests running but get the following error for every test file

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    <redacted>/open-source/graphql-compose/src/utils/__tests__/deepmerge-test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { deepmerge } from '../deepmerge';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1258:14)

```
Am I missing a step to get local development working? I've tried with Node v14.3 and v12.13

**Comment by nodkz** [comment]
Please try to install node_modules via [yarn](https://classic.yarnpkg.com/en/docs/install/#mac-stable). This repo contains yarn.lock file which controls the version of working packages.

Your test case you may put here https://github.com/graphql-compose/graphql-compose/tree/master/src/__tests__/github_issues

Feel free to open Pull Request with the broken test if you don't know how to fix your problem.

**Comment by bkoltai** [comment]
Thanks for the response @nodkz. I've just run `rm -rf node_modules` and then `yarn install` followed by `yarn watch` and get the same result. 😞

**Comment by nodkz** [comment]
Very strange, because it works locally and on CI. What version of NodeJS do you use?

**Comment by bkoltai** [comment]
I'm using `v12.17.0` now but tried with `v14.3.0` and `v10.20.1` as well. Same error with all of them. Have you done a full reinstall of the repo? Delete the entire folder, `git clone`, `yarn install`, and `yarn watch`?

I'm also on Mac and when I `yarn install` with a version >10 I get the [fsevent errors](https://github.com/nodejs/node-gyp/issues/809#issuecomment-473261194) that seem common but not blocking. I didn't get those errors with `v10.20.1`.

**Comment by nodkz** [comment]
Really it's very strange. Please take a look at my video - all works perfectly:
https://youtu.be/2Jb-_wA7rWs

PS. Also, CI for each test run makes fresh repo copy & install.
PSS. Maybe you are using yarn v2? Please try with yarn v1.

**Comment by bkoltai** [comment]
Thanks for the video, still not working for me even after downgrading yarn... oh well. I guess maybe I'll just open an issue with the test I would want to run 😄
