### ISSUE TITLE
How to remove nest args with removeOtherArgs? 

### ISSUE THREAD

**Issue by Quinton** [graphql-compose/graphql-compose#258]
![image](https://user-images.githubusercontent.com/2019808/84099469-445e1e80-aa3c-11ea-9c1e-d2f08e7864ee.png)
I want leave `nickname` arg to delete others. Like this, but not work.
```
UserUpdateOne: UserTC.getResolver('updateOne').removeOtherArgs([ 'record.nickname' ])
```

**Comment by nodkz** [comment]
There is no such ability to remove nested fields via dot-notation. It has quite strange edge cases, for example, what to delete in such case `removeOtherArgs([ 'record.nickname', 'filter', 'meta.name' ])`?!

For now, you may delete nested fields in such way:
```js
UserTC.getResolver('updateOne').getArgTC('record').removeOtherFields('nickname')
```

**Comment by Quinton** [comment]
> There is no such ability to remove nested fields via dot-notation. It has quite strange edge cases, for example, what to delete in such case `removeOtherArgs([ 'record.nickname', 'filter', 'meta.name' ])`?!
> 
> For now, you may delete nested fields in such way:
> 
> ```js
> UserTC.getResolver('updateOne').getArgTC('record').removeOtherFields('nickname')
> ```

@nodkz Awesome 😎 , Thanks for the response.
