### ISSUE TITLE
Subscription resolve never gets fired

### ISSUE THREAD

**Issue by YannisMarios** [graphql-compose/graphql-compose#261]
Hi,

I want to notify my FE app whenever a review gets added, and in my Reviews Schema I have:

```
import { ReviewTC } from '@/models/review'
import ReviewCreateOne from './mutations/reviewCreateOne'
import { reviewCreated } from './subscriptions/reviewCreated'

ReviewTC.addResolver(ReviewCreateOne)

const ReviewQuery = {
  reviewById: ReviewTC.getResolver('findById'),
  reviewMany: ReviewTC.getResolver('findMany'),
  reviewPagination: ReviewTC.getResolver('pagination'),

}

const ReviewMutation = {
  reviewCreateOne: ReviewTC.getResolver('reviewCreateOne'),
}

const ReviewSubscription = {
  reviewCreated,
}

export { ReviewQuery, ReviewMutation, ReviewSubscription }

```

In my schema/index.js

```
import { SchemaComposer } from 'graphql-compose'
import { ReviewQuery, ReviewMutation, ReviewSubscription } from './reviews'
const schemaComposer = new SchemaComposer()

schemaComposer.Query.addFields({
  ...ReviewQuery,
})

schemaComposer.Mutation.addFields({
  ...ReviewMutation,
})

schemaComposer.Subscription.addFields({ ...ReviewSubscription })

export default schemaComposer.buildSchema()
```

in my reviewCreateOne.js resolver:

```
import { ReviewTC } from '@/models/review'
import { PubSub } from 'apollo-server-express'

const pubsub = new PubSub()

export default ReviewTC.getResolver('createOne').wrapResolve(
  (next) => (rp) => {
    pubsub.publish('reviewCreated', {
      reviewCreated: 'review',
    })
    return next(rp)
  },
  'reviewCreateOne'
)
```

and in reviewCreated.js subscription: 

```
import { PubSub } from 'apollo-server-express'
import { ReviewTC } from '@/models/review'

export const reviewCreated = {
  type: ReviewTC,
  resolve: (payload) => {
    console.log('Resolve')
    return payload.reviewCreated
  },
  subscribe: () => {
    console.log('Subscribe')
    const pubsub = new PubSub()
    return pubsub.asyncIterator('reviewCreated')
  },
}
```
 Client app gets subscribed: 

![image](https://user-images.githubusercontent.com/11289298/84749226-5bfc5080-afc2-11ea-9d7f-ee7e1707ba7c.png)

I use the Playground to create a review but the resolve method of reviewCreated never gets fired..

Any ideas?

Thank you

**Comment by YannisMarios** [comment]
Anyone? Is this project supported?

**Comment by nodkz** [comment]
Your code looks legit. And I don't know where you have a problem.

We are widely using subscriptions in our internal apps. As public working example you may look the following repos:
- server https://github.com/graphql-compose/graphql-compose-examples/blob/master/examples/northwind/schema.js#L122
- client https://github.com/nodkz/example-apollo3

**Comment by YannisMarios** [comment]
@nodkz Thank you for your reply. I will look at these problems and let you know.

**Comment by YannisMarios** [comment]
@nodkz 

Hi,

Forgive me if I am wrong but shouldn't this resolve function fire in your example?

![Screenshot_1](https://user-images.githubusercontent.com/11289298/85417220-161e2a00-b578-11ea-8644-32f6c25266cb.png)


Thank you

**Comment by YannisMarios** [comment]
I found what the problem was. I was using two instances of PubSub (const pubSub = new PubSub()) one in my subscription reviewCreated.js file and another on in my resolver reviewCreateOne.js .
