### ISSUE TITLE
join-monster integration ?

### ISSUE THREAD

**Issue by jeanpul** [graphql-compose/graphql-compose#266]
Hi,

Is there any way to use join-monster with createObjectTC ? This require extra fields support :
```
createObjectTC({
  name: 'User',
  sqlTable: 'accounts', // join monster extra fields
  uniqueKey: 'id',` // idem
  fields: {
     email: {
      type: GraphQLString,      
      sqlColumn: 'email_address' // idem 
    },
    ...
  }
})

```
These extra fields will be retrieved by join-monster into the info argument of the resolver.

Thx

**Comment by nodkz** [comment]
Nope. `join-monster` is quit outdated lib and how I know it's unmaintained any more.

`graphql-compose` supports `extensions` property for types. So the recommended way to extend GraphQL types in 2020 is (like it recommended in graphql-js repo):

```
createObjectTC({
  name: 'User',
  extensions: {
      sqlTable: 'accounts', // join monster extra fields
      uniqueKey: 'id',` // idem
  },
  fields: {
     email: {
      type: GraphQLString,      
      extensions: {
          sqlColumn: 'email_address' // idem 
      },
    },
    ...
  }
})
```

But such format does not support `join-monster`.
