### ISSUE TITLE
Resolver for ObjectTypeComposer that implements an Interface

### ISSUE THREAD

**Issue by Tyrubias** [graphql-compose/graphql-compose#268]
I'm writing a discussion forum with several types (such as `Event`, `Notice`, and `Job`) that implement a `PostInterface` interface. I want to write a resolver that will create `Event`s, `Notice`s, and `Job`s without having to write a separate resolver for each type. My resolver takes a custom input type with the fields necessary and returns a payload of `PostInterface`.

However, when I run the resolver, I get the message that `Abstract type PostInterface must resolve to an Object type at runtime. Either the PostInterface type should provide a resolveType function or each possible type should provide an isTypeOf function`.

Is there something I'm doing that's conceptually wrong? How would I write a `resolveType` function?

**Comment by nodkz** [comment]
Conceptually everything is correct.
I think that the problem with the `PostInterface` type. For InterfaceTypeComposer try to use `addTypeResolver` method:
https://github.com/graphql-compose/graphql-compose/blob/b7dfd5b459f4faa7193167e3c090961893b3b86b/src/__tests__/InterfaceTypeComposer-test.js#L977-L995

**Comment by Tyrubias** [comment]
Thank you very much. That solved my issue.
