### ISSUE TITLE
Introspection query fails on field arg with defaultValue from enum with internal values

### ISSUE THREAD

**Issue by CodeProKid** [graphql-compose/graphql-compose#280]
Hi there, I believe I've stumbled upon a bug with field args that have a defaultValue set to an Enum value for an Enum that uses [internal values](https://www.apollographql.com/docs/apollo-server/schema/scalars-enums/#internal-values).

Here's a quick example of what the schema generation code looks like:
```javascript
const sc = new SchemaComposer();
sc.createEnumTC({
  name: 'MyEnum',
  values: {
    FIRST_VALUE: {
      value: 'first_value_mapped',
    },
    SECOND_VALUE: {
      value: 'second_value_mapped',
    },
  },
});

const tc = sc.createObjectTC({
  name: 'MyObjectType',
});

tc.addResolver({
  name: 'someField',
  type: 'String',
  args: {
    testArg: {
      type: 'MyEnum',
      defaultValue: 'first_value_mapped',
    },
  },
  resolve: () => 'test return',
});

tc.addFields({
  someField: tc.getResolver('someField'),
});
```

The schema will get generated as expected:
```graphql
enum MyEnum {
  FIRST_VALUE
  SECOND_VALUE
}

type MyObjectType {
  someField(testArg: MyEnum = FIRST_VALUE): String
}
```
but when Apollo server boots up, it tries to run the introspection query which returns the error:
`GraphQLError: Enum "MyEnum" cannot represent value: "FIRST_VALUE"`
Here is the stack trace:
```
at GraphQLEnumType.serialize (node_modules/graphql/type/definition.js:999:13)
    at astFromValue (node_modules/graphql/utilities/astFromValue.js:136:27)
    at resolve (node_modules/graphql/type/introspection.js:432:57)
    at resolveFieldValueOrError (node_modules/graphql/execution/execute.js:502:18)
    at resolveField (node_modules/graphql/execution/execute.js:460:16)
    at executeFields (node_modules/graphql/execution/execute.js:297:18)
    at collectAndExecuteSubfields (node_modules/graphql/execution/execute.js:748:10)
    at completeObjectValue (node_modules/graphql/execution/execute.js:738:10)
    at completeValue (node_modules/graphql/execution/execute.js:626:12)
    at completeValue (node_modules/graphql/execution/execute.js:592:21)
```
It seems like the issue is coming from [this change](https://github.com/graphql/graphql-js/pull/2334) made in the graphql-js 15.0.0 release.

I'm currently using graphql-js 15.3.0, and graphql-compose 7.16.1.

**Comment by nodkz** [comment]
According to your case, everything works ok – https://codesandbox.io/s/keen-feynman-lz07x?file=/src/schema.js

<img width="1441" alt="Screen Shot 2020-09-22 at 14 20 15" src="https://user-images.githubusercontent.com/1946920/93859045-eb5e8180-fcde-11ea-9583-06a2d819652c.png">

**Comment by Lpaydat** [comment]
Faced the similar issue but with the custom sort of the connection.

It throw an error that look like this:
`GraphQLError [Object]: Enum "SortEnumTypeName" cannot represent value: { fieldOne: -1, fieldTwo: -1 }`.

**Comment by nodkz** [comment]
@Lpaydat can you provide a codesandbox example of your case like above?
