### ISSUE TITLE
Filter if array includes string

### ISSUE THREAD

**Issue by fabian-st** [graphql-compose/graphql-compose#282]
Hi,

I would like to to add a filter arg to a resolver generated by graphql-compose-mongoose, which checks if an array field includes a specific value.

The schema being used is the following:

```js
const EventSchema: Schema = new Schema({
    timestamp:     { type: Date, required: true },
    level:         { type: String, required: true, enum: LEVELS},
    message:       { type: String, required: true },
    meta: {
        topic: { type: String },
        subjects: { type: [String] }
    }
}, { collection: 'events' });
```

Specifically, I would like to check wether meta.subjects includes a specific string.
What I've come up with from another issue is the following:

```js
const _EventTC = composeWithMongoose(Event);

_EventTC.getResolvers().forEach((resolver) => {
    resolver.addFilterArg({
        name: 'subjects',
        filterTypeNameFallback: 'FilterInSubjectsInput',
        type: '[String]',
        query: (query, value, resolveParams) => {
            query.meta.subjects = { $elemMatch: { $in: value } };
        }
    });

    _EventTC.setResolver(resolver.name, resolver);
});

export const EventTC = _EventTC;
```

Unfortunately, using the 'subjects' argument does not affect the results.
How do I achieve this?

Thanks in advance!

**Comment by nodkz** [comment]
Please try with the following change and write here helps it or not:

```diff
- query.meta.subjects = { $elemMatch: { $in: value } };
+ query['meta.subjects'] = { $elemMatch: { $in: value } };
```

**Comment by fabian-st** [comment]
Tried it, but with no success.
Maybe the reason isn't even the query itself, but something different.
The subjects arg appears in GraphiQL, but any console.log()'s from inside the query callback are not printed.

Dumping the filter args gives the following:
```json
{
  type: InputTypeComposer {
    schemaComposer: SchemaComposer {
      types: [Map],
      _schemaMustHaveTypes: [],
      _directives: [Array],
      typeMapper: [TypeMapper]
    },
    _gqType: GraphQLInputObjectType {
      name: 'FilterFindManyEventInput',
      description: '',
      extensions: undefined,
      astNode: undefined,
      extensionASTNodes: undefined,
      _fields: [Function: bound defineInputFieldMap]
    },
    _gqcFields: {
      timestamp: [Object],
      level: [Object],
      message: [Object],
      meta: [Object],
      _id: [Object],
      _ids: [Object],
      _operators: [Object],
      OR: [Object],
      AND: [Object],
      subjects: [Object]
    },
    _gqcExtensions: {}
  },
  description: 'Filter by fields'
}
```

**Comment by nodkz** [comment]
If field was added to the schema then it means that you use the correct resolver setup. So need to debug what exactly query executes mongoose. It can be done in the following way:
```js
import mongoose from 'mongoose';
mongoose.set('debug', true);
```
So you will see queries to MongoDB in the terminal and you may check their correctness.

**Comment by fabian-st** [comment]
Wether or not the subjects filter is specified, the query looks like this:

```
Mongoose: events.find({}, { limit: 1000, projection: { timestamp: true, level: true, message: true }})
```

So no filters are specified.

**Comment by nodkz** [comment]
Hm, it looks like other resolver wrappers in your code clear `query` or replace/remove `resolve` code added by `addFilterArg` method.

Also, you may call `composeWithMongoose` several times like in this issue https://github.com/graphql-compose/graphql-compose/issues/195#issuecomment-512883890

**Comment by fabian-st** [comment]
Hmm this could be, even though the arg 'subject' is being added.
I will retry in a completely blank project and see if it works later. Thanks for now!

**Comment by fabian-st** [comment]
I created this very basic example:https://hastebin.com/ixapayegit.js
package.json: https://hastebin.com/odopuvupuj.json

The mongoose model, as well as the filter arg parameters are the same as mentioned before.
Still, using the subjects filter does not influence the resulting query:
```
Mongoose: events.find({}, { limit: 1000, projection: { message: true, level: true, meta: true } })
```

<img width="1066" alt="Bildschirmfoto 2020-09-06 um 10 45 59" src="https://user-images.githubusercontent.com/67522364/92321971-b390e200-f02e-11ea-8667-a4b0ae809482.png">

**Comment by nodkz** [comment]
Thanks for repro case. The problem in your code:

```diff
EventTC.getResolvers().forEach((resolver) => {
-  resolver.addFilterArg({
+  const newResolver = resolver.addFilterArg({
    name: 'subjects',
    filterTypeNameFallback: 'FilterEventInput',
    type: '[String]',
    query: (query, value) => {
      query['meta.subjects'] = { $elemMatch: { $in: value } };
    },
  });

-  EventTC.setResolver(resolver.name, resolver);
+  EventTC.setResolver(resolver.name, newResolver);
});
```

### Explanation: 

`addFilterArg` – return a new Resolver. By design you able to use the old one for other cases. And you may create as many resolver clones with custom logic as you need:

```ts
const newResolver = resolver.addFilterArg({ ... });
EventTC.setResolver('findManyWithSubject', newResolver);
```

But sometimes you need override existed resolvers. Like in your example. So in such case for proper wrapping, you need to replace the old resolver by a new instance, as I did in the diff above.

**Comment by nodkz** [comment]
Working test case was added to `graphql-compose-mongoose` repo: https://github.com/graphql-compose/graphql-compose-mongoose/blob/alpha/src/__tests__/github_issues/282-test.ts

**Comment by fabian-st** [comment]
Quick response & solution as usual! Again, thanks for helping me out 🥇
