### ISSUE TITLE
Unable to get Types(typescript) to work with addResolver....

### ISSUE THREAD

**Issue by natac13** [graphql-compose/graphql-compose#286]
I am not very sure how to make the types line up with `addResolver` on a TC. My setup is like so.
`model.ts`
```js

// mongoose schema and model creation like expected
const Member = mongoose.model<MemberDoc>('Member', memberSchema)
export const MemberTC = composeMongoose<MemberDoc, MyContext>(Member)
```
`schema.ts`
```js
MemberTC.addResolver({
  name: 'login',
  description: 'Login method for members.',
  type: LoginResult.getType(),
  args: LoginInput.getFields(),
  resolve: async ({ context, projection, args }) => {
    try {
      const $project = dotifyWithAliases(projection.Member)
      const { member } = await context.dataSources.Member.login(args, $project)
      const { token } = await context.login(context, member)
      return {
        __typename: 'LoginSuccessResult',
        Member: member,
        token
      }
    } catch (err) {
      return {
        __typename: 'SimpleResult',
        success: false
      }
    }
  }
})
```

The resolve function does not have any types defined. I have to add `: ResolverResolveParams<Member, MyContext, Record<string, typeof LoginInput>>` to make it work... 
Is this what is expected? Or am I doing something wrong?
I full typescript example would be greatly appreciated. And if I can get this working I would like to help with the example to help others avoid this headache.

Plus the return type of the resolve function is not checked... I would expect that the type field with LoginResult.getType() would fill out the autocomplete. No luck...

**Comment by nodkz** [comment]
`addResolver` logic was created 3-4 years ago. And now in the TypeScript world, I find this pattern very bad. So I decided to start migration on a more simple, obvious pattern – just use a simple JS object (resolver factory) which will not have current TS issues. And moreover, solve some `clone` resolve problems. More info can be found here https://github.com/graphql-compose/graphql-compose-mongoose/issues/263

You already can try these changes with graphql-compose-mongose@9.0.0-alpha.10
As `latest` tag it will be published in couple weeks, when we migrate half of our code base on new pattern and will be satisfied.

I try to prepare release notes for 9.0.0 on this or next week. It will be nice if you can review it. Thanks.

Full list of changes: https://github.com/graphql-compose/graphql-compose-mongoose/milestone/1?closed=1

**Comment by natac13** [comment]
>You already can try these changes with graphql-compose-mongose@9.0.0-alpha.10

I have already started a branch to convert my graphql server over to graphql-compose-mongoose. I believe I have a good understanding of how to utilize your two library to handle a lot of the work I was doing. :clap: Very excited for the new release.

>I try to prepare release notes for 9.0.0 on this or next week. It will be nice if you can review it. Thanks.

Whatever I can do to help.

**Comment by nodkz** [comment]
Yep, i recommend not to use `addResolver` method.

Another approach recommended in v9.0.0 release notes for graphql-compose-mongoose.

Let close this issue and continue discussion in https://github.com/graphql-compose/graphql-compose-mongoose/pull/273#issuecomment-699491314
