### ISSUE TITLE
Possible invalid return type for `ObjectTypeComposer.getRelations`

### ISSUE THREAD

**Issue by danez** [graphql-compose/graphql-compose#291]
I was looking at the code to fix an [issue](https://github.com/graphql-compose/graphql-compose-mongoose/pull/276) in `graphql-compose-mongoose` and noticed that the return type for `ObjectTypeComposer.getRelations` is possibly wrong.

It is currently defined as `ObjectTypeComposerRelationThunkMap`, but nowhere in the code I can see that `ObjectTypeComposer. _gqcRelations` (which has the same type) gets thunks added. I think that It should be a normal map of `relationName => options`.

I could be of course mistaken, but I checked all usages of `_gqcRelations` and didn't see any thunk related code. I see that fields have a proxy/thunk thing going on but that never touches relations I think.

I can create a PR if someone can confirm this.

https://github.com/graphql-compose/graphql-compose/blob/master/src/ObjectTypeComposer.js#L1710
https://github.com/graphql-compose/graphql-compose/blob/master/src/ObjectTypeComposer.js#L215

**Comment by nodkz** [comment]
@danez yep, you are right! 👍
I fixed it by myself for speeding up PR for graphql-compose-mongoose.
A new GC package will be published in a couple of minutes.

**Comment by danez** [comment]
Wow that was fast thanks.
