### ISSUE TITLE
Filter Query Operators

### ISSUE THREAD

**Issue by jovermier** [graphql-compose/graphql-compose#292]
There seems to be no clear way to add query operators such as mongo's $eq, $gt, $gte, $in, $lt, $lte, $ne, $nin.

Example syntax would be
`{ <field>: { EQ: <value> } }`
`{ <field>: { GT: <value> } }`

The ideal graphql query would be
`inventory(filter: { tags: { NIN: [ "appliances", "school" ] } })`

or an even more advanced query
```
query {
  inventory(
    filter: {
      AND: [
        { tags: { NIN: ["appliances", "school"] } }
        { price: { GT: 10 } }
        { canBeSold: { EQ: true } }
      ]
    }
  ) {
    id
  }
}
```

**Comment by nodkz** [comment]
This issue related to `graphql-compose-mongoose` package and discussed here https://github.com/graphql-compose/graphql-compose-mongoose/issues/277
