### ISSUE TITLE
There should be a way to preserve unused types on `buildSchema()`

### ISSUE THREAD

**Issue by craicoverflow** [graphql-compose/graphql-compose#293]
I have a use case where I need my GraphQL schema (composed using this library) to keep all unused types in the schema when I run [`buildSchema()`](https://graphql-compose.github.io/docs/api/SchemaComposer.html#buildschema).

The only way I can see to achieve this is by adding the types I want to a "keep" list with [`addSchemaMustHaveType`](https://graphql-compose.github.io/docs/api/SchemaComposer.html#addschemamusthavetype). The problem with this is that only those types that are explicitly added with this method are kept, whereas I want all types to be kept (some of which already exist in the initial schema).

I was looking to create a PR to help with this, but was unsure where would be the best to do it in the current architecture - [`ExtraSchemaConfig`](https://graphql-compose.github.io/docs/api/SchemaComposer.html#extraschemaconfig) does not feel like an appropriate interface to extend since it is essentially a proxy to [GraphQLSchemaConfig](https://github.com/graphql/graphql-js/blob/01bcc7d9be982226bcf56b8f983f38fd89dced1b/src/type/schema.d.ts#L125).

I'd love to help, but don't want to jump in just yet! Maybe this does not require a code solution at all?

**Comment by nodkz** [comment]
Feel free to extend `ExtraSchemaConfig` with a new additional option (eg. `keepAllTypes: true` or `addAllTypes: true` or any another better name on your choice). Just extract this option in SchemaComposer.buildSchema before passing rest options to graphql.buildSchema.
