### ISSUE TITLE
Document what non-directive extensions actually are

### ISSUE THREAD

**Issue by wheresrhys** [graphql-compose/graphql-compose#306]
It's a bit confusing at present. 
1. Extensions in the graphql-compose sense appears to have nothing to do with the `extend` operator in GraphQL. There is nothing in the GraphQL spec about extensions in the graphql-compose sense, adn nothing in your docs I've been able to find either.
2. There are no examples of what extensions might be used for or what outputs are possible with them. I'm guessing they are mainly intended for annotating aspects of a schema with metadata, but this doesn't get carried through to SDL. It'd be good to document the limitations
3. The tests & typedefs aren't much help either - they more or less just assert that the extensions APIs are self-consistent

**Comment by nodkz** [comment]
`Extensions` is a property on type/field/arg definitions to pass private extra metadata.
It's used only on the server-side with the Code-First approach, mostly for 3rd party middlewares & plugins.
Property `extensions` may contain private server metadata of any type (even functions)
and does not available via SDL.

If you need to provide public metadata to clients then use `directives` instead.
@see https://github.com/graphql/graphql-js/issues/1527
