### ISSUE TITLE
Directive "@deprecated" for arguments in SDL is ignored

### ISSUE THREAD

**Issue by vladar** [graphql-compose/graphql-compose#317]
Looks like the `@deprecated` directive for arguments in SDL is ignored. Check out the example:

```js
const typeComposer = typeMapper.convertSDLTypeDefinition(`
  type Foo {
    foo(
      arg: String @deprecated(reason: "Tired")
    ): String
  }
`);
```

Now if I try building this type it renders without the `@deprecated` directive:

```js
import { printType } from "graphql";

printType(typeComposer.getType());

// prints this:
//   type Foo {
//     foo(arg: String): String
//   }
```

I wanted to fix it and open a PR but looks like this is intentional:

https://github.com/graphql-compose/graphql-compose/blob/bd3bc96f32e303e6257cd9d94dcd4d61f8805c12/src/TypeMapper.js#L1120-L1124

So not sure what is the best course of action here. Any thoughts?

**Comment by nodkz** [comment]
I've spent several hours trying to figure out this problem without lack.
If we remove this logic the the test 254 fails with the following error (duplication of `deprecated` directive):
<img width="709" alt="Screen Shot 2021-02-12 at 02 59 29" src="https://user-images.githubusercontent.com/1946920/107698353-a1525880-6cde-11eb-957a-6da8d6d4718c.png">

**Even more, there is another problem with directives for args. When I remove 1120-1124 lines then `printType` method does not add directive properly.**

@vladar may I ask you to open a new PR with your fix? Please ignore the 254 test suite I'll fix it myself and add the following test suite:

```
/* @flow */

import { printType } from 'graphql';
import { schemaComposer, dedent } from '../..';

describe('github issue #317: Directive @deprecated for arguments in SDL is ignored ', () => {
  it('should build schema successfully', async () => {
    const typeComposer = (schemaComposer.typeMapper.convertSDLTypeDefinition(`
      type Foo {
        foo(
          arg: String @deprecated(reason: "Tired")
        ): String
      }
    `): any);

    const type = typeComposer.getType();

    expect(printType(type)).toEqual(dedent`
      type Foo {
        foo(
          arg: String @deprecated(reason: "Tired")
        ): String
      }
    `);
  });
});
```

**Comment by vladar** [comment]
I switched to something else at the moment. But will try to come up with a PR next week.
