### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by rifton007** [graphql-compose/graphql-compose#326]
The topic about the Interface is not clear for me.
Can someone to give me explain and a exemple to create and use a Interface with graphql-compose.

https://graphql-compose.github.io/docs/basics/understanding-types.html#interfaces-via-interfacetypecomposer
_For exemple, I don't understand this parts `value => (value instanceof UserDoc)` and where from `UserDoc` ?_

**Update message**

After some hours on graphql-compose, I see that some functions are not enough documented with a complete example.
Like `InterfaceTypeComposer` previously, I can't understand also how to use a `inputType` after created it with `InputTypeComposer`.

For the beginer like me, the documentation is well done at the begining, to create schema, query and mutation, that clear.
But when I go to advenced concept like Interface, Input and Union, the explains and examples are not sufficient.

Same things with `"ThunkComposer"` and `"Extensions Methods"`, what is ?

**Update message**

What are the "Field Args methods" used for?
graphql-compose can manage introspection ?

Thanks,

**Comment by rifton007** [comment]
After some hours on graphql-compose, I see that some functions are not enough documented with a complete example.
Like `InterfaceTypeComposer` previously, I can't understand also how to use a `inputType` after created it with `InputTypeComposer`.

For the beginer like me, the documentation is well done at the begining, to create schema, query and mutation, that clear.
But when I go to advenced concept like Interface, Input and Union, the explains and examples are not sufficient.

**Comment by nodkz** [comment]
Sorry for the late response. I don't have enough free time to polish all things.

> graphql-compose can manage introspection ?

Yes and no. Before calling `schemaComposer.buildSchema()` you may change your types as you wish even removing any field. For example, via `graphql-compose-mongoose` generator you may create graphql types & resolvers from mongoose schema; and before schema construction, you may remove/add/modify any field.

> Same things with "ThunkComposer" and "Extensions Methods", what is ?

`ThunkComposer` - it's an internal wrapper that helps to solve hoisting problems when several javascript modules imports each other. ThunkComposer used internally and unwraps only when you call `schemaComposer.buildSchema()`.

Extensions Methods – methods that allow manipulation of some additional data (configuration options, callback etc like Directives) in GraphQL types. In graphql-js it was added in https://github.com/graphql/graphql-js/pull/2097. And discussed in https://github.com/graphql/graphql-js/issues/1527 and https://github.com/graphql/graphql-js/issues/1343

> Can someone to give me explain and a exemple to create and use a Interface with graphql-compose.


Before returning data from resolver graphql want to determine which exact Type should be used for returning data. 
You may take a look at this test case
https://github.com/graphql-compose/graphql-compose/blob/58a5d46b2fb29cd16fd668b6f5e0ee806fb56154/src/__tests__/InterfaceTypeComposer-test.ts#L1125

**Comment by rifton007** [comment]
Thanks, success for your work.
