### ISSUE TITLE
Modify output of mongooseResolvers

### ISSUE THREAD

**Issue by dan-cooke** [graphql-compose/graphql-compose#340]
Hi there,

Apologies if this has been documented somewhere ( I am struggling to find it)

Is there any easy way to modify the output structure of the mongoose resolvers.

For compatibility with ApolloClient cache, it would be useful if the mongoose mutation resolvers returned just the `record` type.

### Example
The current structure returned is

```
{
    error {
      message
    }
    recordId 
    record {
      _id
      owner
    }
  }
```

I would like to return

```
{
    _id
    owner
 }
```

I am aware that I can just create my own resolver and do this manually, but I would prefer a solution using `wrapResolve` perhaps, that way I can reuse this throughout my codebase.

**Comment by nodkz** [comment]
> For compatibility with ApolloClient cache, it would be useful if the mongoose mutation resolvers returned just the record type.

The current shape of the response is compatible with the ApolloClient cache. `record` field has the proper type which correctly updates your data in normalized apollo cache.

This shape is following to following rules https://graphql-rules.com/rules/mutation-payload

**Comment by dan-cooke** [comment]
@nodkz  thanks for the swift reply!

That is very interesting, my bad. I just realised I made a stupid mistake in my frontend.

For anyone who is here from Google - heres are some docs to modify the output of a resolver using `wrapResolve` simply

https://graphql-compose.github.io/docs/basics/what-is-resolver.html#how-resolverwrapresolve-work-internally
