### ISSUE TITLE
How create reuse resolvers

### ISSUE THREAD

**Issue by rifton007** [graphql-compose/graphql-compose#345]
[Why do we need the Resolver?](https://graphql-compose.github.io/docs/basics/what-is-resolver.html#why-do-we-need-the-resolver)
> Resolvers helps to describe CRUD operations logic only once and then reuse them in different scenarios. For Query.authorById provides its full functionality from findById resolver. For Post.author you wrap findById resolver where should be hidden id arg and its value automatically will be set from post.authorId. For wrapping Resolvers graphql-compose provides a bunch of methods.

I want do that, but without succed

```js
// reuse resolvers "resolvers.js"
const {schemaComposer} = require('graphql-compose');
const find = schemaComposer.createResolver({
	name: 'find',
	kind: 'query',
	args: {
		filter: 'String',
		order: 'String'
	},
	resolve: async ({source, args, ctx, info}) => {
		console.log(source, args, ctx, info);
	}
});
module.exports = {find}
```

```js 
// objectType "types.js"
const {find} = require('../resolvers')
UsersTC.addResolver(find);
PostsTC.addResolver(find);
```
```js
// Queries "server.js"
schemaComposer.Query.addFields({
	users: UserTC.getResolver('find', [middleware.isAuth]), // Error: fieldTC "users" is not defined`
	posts: PostTC.getResolver('find', [middleware.isAuth]), // Error: fieldTC "posts" is not defined`
});
```
What are wrong here ?
Thanks,

**Comment by oklas** [comment]
Your resolver is not returning a value and have not type field. But what is the problem or error exactly?

**Comment by oklas** [comment]
Your resolver is not returning a value and has not type field. But what is the problem or error exactly?

**Comment by rifton007** [comment]
Thank you @oklas 
> Your resolver is not returning a value.

Yes I know, I put just a first `console.log()` to understand how it works. 

> Has not type field.

This is a little confuse for me, the resolver has not type field because it is dynamic (can be `UserTC` or `PostsTC` )

> what is the problem or error exactly?

I tried several unsucces approch  to do that, but the current error is :
```js
users: UserTC.getResolver('find', [middleware.isAuth]) // Error: fieldTC "users" is not defined`
```

**Comment by oklas** [comment]
Typically field `type` has type composer like this:

```js
{
  type: UsersTC,
  ...
}
```

Because of this, the mentioned error:

> ```js
> users: UserTC.getResolver('find', [middleware.isAuth]) // Error: fieldTC "users" is not defined`
> ```

mean exactly that "type composer of field users" (`fieldTC`) is not defined, (that is defined in field `type` as above)

One of the way you can use is a resolver factory that you can create:

```js
const findResolverFactory = type => schemaComposer.createResolver({
  type,
  name: 'find',
  ...  
})

UsersTC.addResolver(findResolverFactory(UserTC))
PostsTC.addResolver(findResolverFactory(PostsTC))

```
