### ISSUE TITLE
Question-Adding Custom Params to Middleware

### ISSUE THREAD

**Issue by MDrooker** [graphql-compose/graphql-compose#354]
Noob Question-
Im using the basic middleware param feature on the ObjectTypeComposer.getResolver method-
Looks like -
```  updateEventQuestionAnswer: EventQuestionAnswerTC.getResolver('updateOne', [schemaUtils.purgeCache]),```

But I need to pass a few params to my purgeCache function to get the reuse of out it I'm looking for.
Each of the Mutations/Queries may have different params that the purgeCache function would need...which is why I need to pass different ones per ```getResolver```

I know I can do a ```wrapResolver``` and do it that way...but looking for the cleanest method of reuse.

**Comment by nodkz** [comment]
How about this

```ts
function initPurgeCache(opts) {
  return schemaUtils.purgeCache ...;
}

update1: EventQuestionAnswerTC.getResolver('updateOne', [initPurgeCache({ ttl: 10 })]),
update2: EventQuestionAnswerTC.getResolver('updateMany', [initPurgeCache({ ttl: 20 })]),
```

**Comment by MDrooker** [comment]
Well damn...When you put it that way-  
Makes total sense.
Hate I missed this
Thank you
