### ISSUE TITLE
Arguments set in wrapResolve are not cleared after request

### ISSUE THREAD

**Issue by amylashley** [graphql-compose/graphql-compose#358]
We are on v7.0.4 which is required by the elasticsearch and pagination components we use. We've noticed an unexpected behavior with how arguments are handled within the wrapResolve method and am hoping to get some insight as to why. Here is an example code: 
```
  ExampleTC.addRelation('example_relation', {
    resolver: (_, args, context) => 
    RelationTC.getResolver('someResolver').wrapResolve(next => async rp => {
      if (condition) {
       // add something to the filter object
        rp.args.filter["other_filters"] = [ {"id" : {"in": idList}} ]
      } 
      return next(rp);
    }),
    prepareArgs: {
      filter: {
        "root_filters":[{"type": {"notLike": "somevalue"}}],
      }    
    }
  })
```
We're seeing that if on one request the  rp.args.filter["other_filters"] has been set, then it is ALWAYS set in the next request too, even when that condition inside wrapResolve is not met. We are able to fix this by moving the filter init out of prepareArgs and always initializing it inside wrapResolve. We're just wondering why that seems to be cached otherwise. Thanks!

**Comment by nodkz** [comment]
First of all, you have a small problem with resolver definition:

```diff
  ExampleTC.addRelation('example_relation', {
-    resolver: (_, args, context) =>
+    resolver: (schemaComposer) => 
```

But the real problem is that you are modifying [`argsProto` variable from prepareArgs](https://github.com/graphql-compose/graphql-compose/blob/15af64cdd3d619a3359033a6f5a1f210989fd0fd/src/ObjectTypeComposer.ts#L1876). 

So you need to change your code in following manner
```diff
      if (condition) {
       // add something to the filter object
-        rp.args.filter["other_filters"] = [ {"id" : {"in": idList}} ]
+       rp.args.filter = { ...rp.args.filter, other_filters: [ {"id" : {"in": idList}} ] };
      } 
      return next(rp);
```

**Comment by amylashley** [comment]
Ahhhh! @nodkz thank you very much! this makes sense. Also- I've always used that resolver definition so thanks, schemaComposer there also makes sense.
