### ISSUE TITLE
Point release to resolve `object-path` security alerts

### ISSUE THREAD

**Issue by aaronadamsCA** [graphql-compose/graphql-compose#369]
The version of `object-path` on the main branch is up to date, but the version in v9.0.4 is outdated and now has two open CVEs, high and moderate severity.

A point release would be nice, just to bump the deps and quiet the alerts.

**Comment by nodkz** [comment]
Thanks for reporting. It's not the first severity alert of this package. 

It was the last alert from this package because I get rid of it completely.
