### ISSUE TITLE
getComposeTypeName: issue with reported error when misc.inspect itself throws an error

### ISSUE THREAD

**Issue by kije** [graphql-compose/graphql-compose#372]
Hi, I have a somewhat strange and probably not so common issue.

I use gatsby as a framework for my website, which internally uses [graphql-compose](https://github.com/graphql-compose/graphql-compose).
Now I had an issue where there an error occurred in [getComposeTypeName](https://github.com/graphql-compose/graphql-compose/blob/c1ec2f2a8ada13a11c0e7eb192447b2cc0d4b9c1/src/utils/typeHelpers.ts#L340). 
This invoked the catch block there, where `inspect` is called (presumably in order to generate a helpful error message). However, in my case, inspect itself threw an error (namely a Maximum call stack size exceeded error, since the object inpect was trying to print was a complex object (a huge graphql schema)).

This lead to only the Maximum call stack size exceeded error being reported, and debugging the root cause of the issue was really time-consuming and difficult.

Maybe it would be a good idea to wrap the inspect call there again in a try/catch, and if inspect then trows an error, report just the message from the original error?

```typescript
export function getComposeTypeName(type: any, sc: SchemaComposer<any>): string {
  if (typeof type === 'string') {
  // ..
  } else if (isFunction(type)) {
    return getComposeTypeName((type as any)(sc), sc);
  } else {
    try {
      const gqlType = getGraphQLType(type) as any;
      if (typeof gqlType.name === 'string') {
        return gqlType.name;
      }
    } catch (e) {
      try {
        throw new Error(`Cannot get type name from ${inspect(type)}`);
      } catch (innerError) {
        throw new Error(`Cannot get type name from <unknown>. (original error: ${e.message})`);
     }
    }
  }

  throw new Error(`Cannot get type name from ${inspect(type)}`);
}
```

**Comment by pieh** [comment]
Heh, I was debugging same thing today, and seeing this issue would help me save some time finding root of the problem :) In any case I did open https://github.com/graphql-compose/graphql-compose/pull/373 with a change that seemed to work for me
