### ISSUE TITLE
Is it possible to generate the types with the Native MongoClient with nodeJS 

### ISSUE THREAD

**Issue by riginoommen** [graphql-compose/graphql-compose#375]
https://www.npmjs.com/package/mongodb#:~:text=const%20%7B%20MongoClient%20%7D%20%3D%20require(%27mongodb%27)%3B

**Comment by nodkz** [comment]
This package does not support Native MongoClient.
Mongoose schema is used as a source for describing types. Native MongoCient does not have a schema.
