### ISSUE TITLE
Changes in graphql-compose@2.0.0

### ISSUE THREAD

**Issue by nodkz** [graphql-compose/graphql-compose#66]
### Removed build phase of relations from graphql-compose:
Now relations works via the construction of custom graphql thunk for the field-configs-map. This thunk resolves when `graphql-js` builds schema. No more need in a special phase of graphql-compose when it prepares relations (eg. `GQC.buildSchema()` or `TC.buildRelations()`). It means that constructed GraphQLObjectTypes via `graphql-compose` (eg. `UserTC.getType()`) may be safely used in any place of manually defined `graphql-js` schema or in 3rd party schema generation tools.

So if you use methods `TC.buildRelation('field')`, `TC.buildRelations()` or `GQC.buildRelations()` - just remove them. This methods marked as deprecated for 3.0.0.

### Refactored `TC.addRelation(fieldName, opts)` method:
1) `opts` became regular object
2) `opts.resolver` now is thunk. It solves hoisting problems with
cross imported modules.
3) `opts.args` renamed to `opts.prepareArgs`. Better naming, cause `args` used for GraphQLArgsConfigMap, but here is a special instruction how to prepare args of existed Resolver. Removing misunderstanding.

```diff
- UserTC.addRelation('lastArticle', () => {
+ UserTC.addRelation('lastArticle', {

-  resolver: ArticleTC.getResolver('findOne'),
+  resolver: () => ArticleTC.getResolver('findOne'),

-  args: { /* ... */ },
+  prepareArgs: { /* ... */ },
});
```
You may see how was upgraded `graphql-compose-examples` on v2.0.0 [here](https://github.com/nodkz/graphql-compose-examples/commit/9c94877c2573ad22612b11b887a8bffe4006fe94).

### `.getField()`, `.getFieldArg()`, `.extendField()`, `.get()` now throw an error if field does not exist:
This change provides better dev experience:
- the more strict schema definition. No guessing what is wrong schema construction when errors occur on schema start up.
- more pleasant Flowtype checks in your app code and plugins (no need to check is field defined or not after eg. `.getField` method) 

You may catch this errors or use `TC.hasField()` method for checking field presence.

### Removed methods and options which were marked as deprecated for 2.0.0:
If somebody uses these deprecated methods, they got console warnings. Now it completely removed. List of removed methods: https://github.com/nodkz/graphql-compose/commit/0ebd5b32fd70f2ab481c064483fa933cfb630e5c

### Other fresh changes, which landed in June 2017 
- I spent a lot of time on resolving thousands of Flowtype errors between graphql-js, graphql-compose and graphql-compose-[plugins]. Now they should not have errors. Also when you will cover your app scripts with `/* @flow */` you also should not have errors.
- Re-export of `graphql-js`. Now from all `graphql-compose-[plugins]` I removed the `graphql` dependency. Only `graphql-compose` has `graphql` as peerDependency. So if your plugins need `graphql` then it should use `import { graphql } from 'graphql-compose';`. It provides better developer experience, you may link any plugin or graphql-compose itself to your app without internal linking of packages.
- To CI tests were added checks for `eslint` and `flowtype`. It's done cause was added `greenkeeper`. Now when will be updated `graphql-compose`, greenkeeper will automatically open PR for graphql-compose-[plugins] with success updates or will inform me that some tests or flowtype checks fail. The same will be when updates `graphql-js`. The easy way to keep all in sync and green.

### Thoughts/ideas for future
- Write a plugin for traversing graphql schema. Eg. `graphql-compose-visitor`. Which helps to me move on with [graphql-perf](https://github.com/graphql-compose/graphql-perf) and helps with next idea.
- Make new plugin for interoperability of GraphQL provisioned end-points. Discussion can be found [here](https://github.com/OpenGraphQL/opengraphql-organization/issues/1). My idea is to write a graphql compose plugin, which takes some graphql introspection and creates TypeComposer with fields from a query and creates Resolvers from mutations. Also via options provide `prefix` or `postfix` for all types from remote graphql schema (eg. give an ability to rename Github's User type to GithubUser and all other TypeObjects for avoiding collisions of type names in your schema).

**Comment by nodkz** [comment]
@stoffern @yoadsn @zapkub @katopz **please test `graphql-compose@2.0.0-alpha.3` with your app.** 

In my app, I changed only `addRelation()` as described above and all works like a charm. If you will not have bugs too, I'll publish 2.0.0 version. Thanks.

**Comment by yoadsn** [comment]
@nodkz Sorry - was not able to test this yet - will test it soon on master although I will not be able to deploy 2.0 to prod in the next weeks we are under some heavy dev in some other area at the moment.
Thank you so much for those updates - they make total sense.

Regarding future ideas - +1 for the interoperability plugin - I was thinking the same when I saw the [apollo graphlql-tools](https://github.com/apollographql/graphql-tools) schema generation. Is that something like you had in mind?

**Comment by nodkz** [comment]
@yoadsn `apollo graphlql-tools` is another implementation of `graphql-compose`, another way of schema construction/definition. Under `interoperability` I mean plugin or may be several plugins, which takes some data sources (eg. 3rd parties public/private graphql endpoints) and provides to you TypeComposers with built-in Resolvers to this 3rd party data sources. These TypeComposers you may edit, wrap or clean up and put them to your schema.

PS. We have been working for about a week on production with `2.0.0-alpha.3` and have no errors. For me this version is stable. I just published new `2.0.0` version. So if you meet with bugs and problems, feel free to open issues.

**Comment by stoffern** [comment]
i will try it out tomorrow 😉

**Comment by yoadsn** [comment]
@nodkz Looks good - upgrading to 2.0.0 was only fixing the addRelation code indeed.
All working now - will upgrade on the next dependency update cycle.
Thanks!!

**Comment by nodkz** [comment]
Glad to hear that all works.

Don't miss new debug methods for resolvers: https://github.com/nodkz/graphql-compose/releases/tag/v2.1.0 
They are pretty simple and powerful with filtering output fields.

**Comment by stoffern** [comment]
@nodkz I have a complex database with example: car -> roads and roads -> cars where relations are set both ways.

When removing buildRelations one of the relations will not compile and show. Example: roads->cars will not work but car->roads will work.

Am i missing something?

**Comment by stoffern** [comment]
My bad found the problem :)

**Comment by stoffern** [comment]
@nodkz you are a genius! Everything works as expected and there is no bugs as i can find.
Can this be closed?
